#pragma once

#include "sdkconfig.h"

#define CAMERA_MODEL_XIAO_ESP32S3

#define APP_WIFI_SSID           CONFIG_APP_WIFI_SSID
#define APP_WIFI_PASSWORD       CONFIG_APP_WIFI_PASSWORD
#define APP_UPLOAD_URL          CONFIG_APP_UPLOAD_URL
#define APP_UPLOAD_FIELD_NAME   CONFIG_APP_UPLOAD_FIELD_NAME
#define APP_CAPTURE_INTERVAL_MS CONFIG_APP_CAPTURE_INTERVAL_MS
